apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone-deployment
  namespace: dev
  labels:
    release: drone
subjects:
- kind: ServiceAccount
  name: drone-deployment
  namespace: dev
roleRef:
  kind: Role
  name: drone-deployment
  apiGroup: rbac.authorization.k8s.io