
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test
  namespace: system
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
