apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: system
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: test
      mountPath: /data/redis
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: test
  restartPolicy: Always
