apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drone-runner
  namespace: dev
  labels:
    release: drone
spec:
  dnsNames:
    - runner.champiat.lan
  secretName: drone-runner-tls
  issuerRef:
    name: web-ca-issuer
    kind: ClusterIssuer