apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drone
  namespace: dev
spec:
  dnsNames:
    - drone.champiat.lan
  secretName: drone-tls
  issuerRef:
    name: web-ca-issuer
    kind: ClusterIssuer