kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone
  namespace: dev
  labels:
    release: drone
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
