apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pki
  namespace: services
  labels:
    release: pki
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi

