apiVersion: v1
kind: Secret
metadata:
  name: csi-truenas-config
  namespace: system
type: Opaque
stringData:
  driver-config-file.yaml: |
    driver: freenas-api-nfs
    instance_id:
    httpConnection:
      protocol: "https"
      host: "nas.lan"
      port: "443"
      apiKey: "asm.love"
      allowInsecure: true
      apiVersion: 2
    zfs:
      datasetParentName: "data/k3s/nfs"
      detachedSnapshotsDatasetParentName: "data/k3s/snaps"
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      shareHost: "nas.lan"
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: "root"
      shareMaprootGroup: "root"
      shareMapallUser: ""
      shareMapallGroup: ""