# Default values for democratic-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

extraCaCerts:
#extraCaCerts: |-
#  -----BEGIN CERTIFICATE-----
#  ...
#  -----END CERTIFICATE-----
#  -----BEGIN CERTIFICATE-----
#  ...
#  -----END CERTIFICATE-----

driver:
  # see the driver-config-secret.yaml for syntax
  # NOTE: if setting an existing secret you must still set `driver.config.driver`
  # to the corresponding value that you place in the secret as the value is used
  # by the chart for other purposes beyond secret creation
  existingConfigSecret: csi-truenas-config
  config:
    driver: freenas-api-nfs

# https://kubernetes-csi.github.io/docs/csi-driver-object.html
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.api.nfs"
  version: 1.5.0
  # create the kubernetes CSIDriver
  enabled: true
  attachRequired: false
  podInfoOnMount: true
  # https://kubernetes-csi.github.io/docs/support-fsgroup.html
  # k8s 1.19+ (ignored otherwise)
  # None|File|ReadWriteOnceWithFSType
  # fsGroupPolicy: ReadWriteOnceWithFSType
  
  # clusters before k8s 1.14 requeired manual installation
  # kubectl create -f https://raw.githubusercontent.com/kubernetes/csi-api/master/pkg/crd/manifests/csidriver.yaml
  installCRD: false
  
  # k8s 1.16+
  # volumeLifecycleModes: []
  
  # k8s 1.20+
  # tokenRequests: []

  # k8s 1.20+
  # requiresRepublish: false

  # k8s 1.19+
  # storageCapacity: false

controller:
  enabled: true
  rbac:
    enabled: true
    openshift:
      # set to true if running on openshift *and* you have need
      # ie: hostNetwork, hostIPC, etc are turned on
      privileged: false
  replicaCount: 1
  hostNetwork: false
  hostAliases: []
  hostIPC: false
  podAnnotations: {}
  podLabels: {}
  
  # deployment = deploy controller parts in a distinct deployment
  # node       = deploy controller as sidecars with node daemonset
  strategy: deployment

  # https://kubernetes-csi.github.io/docs/external-attacher.html
  externalAttacher:
    enabled: false
    image: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
    args:
    - --v=5
    - --leader-election
    - --leader-election-namespace={{ .Release.Namespace }}
    - --timeout=90s
    - --worker-threads=10
    - --csi-address=/csi-data/csi.sock
    # if you do not want to completely override the defaults use this
    extraArgs: []

  # https://kubernetes-csi.github.io/docs/external-provisioner.html
  externalProvisioner:
    enabled: true
    image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
    args:
    - --v=5
    - --leader-election
    - --leader-election-namespace={{ .Release.Namespace }}
    - --timeout=90s
    - --worker-threads=10
    - --extra-create-metadata
    - --csi-address=/csi-data/csi.sock
    # if you do not want to completely override the defaults use this
    extraArgs: []

  # https://kubernetes-csi.github.io/docs/external-resizer.html
  externalResizer:
    enabled: true
    image: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
    args:
    - --v=5
    - --leader-election
    - --leader-election-namespace={{ .Release.Namespace }}
    - --timeout=90s
    - --workers=10
    - --csi-address=/csi-data/csi.sock
    # if you do not want to completely override the defaults use this
    extraArgs: []

  # https://kubernetes-csi.github.io/docs/external-snapshotter.html
  externalSnapshotter:
    enabled: true
    # 1.20+ should use v4.0.0+
    # READ *before* updating from beta https://github.com/kubernetes-csi/external-snapshotter#usage
    image: k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
    args:
    - --v=5
    - --leader-election
    - --leader-election-namespace={{ .Release.Namespace }}
    - --timeout=90s
    - --worker-threads=10
    - --csi-address=/csi-data/csi.sock
    # if you do not want to completely override the defaults use this
    extraArgs: []

  # https://github.com/kubernetes-csi/external-health-monitor
  externalHealthMonitorController:
    enabled: false
    image: k8s.gcr.io/sig-storage/csi-external-health-monitor-controller:v0.4.0
    args:
    - --v=5
    - --leader-election
    - --leader-election-namespace={{ .Release.Namespace }}
    - --timeout=90s
    - --worker-threads=10
    - --csi-address=/csi-data/csi.sock
    #- --enable-node-watcher
    #- --list-volumes-interval
    # if you do not want to completely override the defaults use this
    extraArgs: []

  # https://kubernetes-csi.github.io/docs/cluster-driver-registrar.html
  # not implemented, likely uncessary at this point
  clusterDriverRegistrar:
    enabled: false

  livenessProbe:
    enabled: true

  # democratic-csi controller
  driver:
    enabled: true
    image: docker.io/democraticcsi/democratic-csi:v1.6.0
    # imagePullPolicy: Always
    logLevel: debug
    lifecycle:
#      postStart:
#        exec:
#          command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
#      preStop:
#        exec:
#          command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]

    securityContext:
#      allowPrivilegeEscalation: true
#      capabilities:
#        add:
#        - SYS_ADMIN
#      privileged: true

    extraEnv: []
    extraVolumeMounts: []
#    - name: foo
#      mountPath: /foo

  extraVolumes: []
#  - name: foo
#    hostPath:
#      path: /dev
#      type: Directory

  nodeSelector: {}

  tolerations: []

  affinity: {}

node:
  rbac:
    enabled: true
    openshift:
      # set to true if running on openshift
      privileged: false
  enabled: true
  hostNetwork: true
  hostAliases: []
  hostIPC: true
  kubeletHostPath: /var/lib/kubelet
  podAnnotations: {}
  podLabels: {}

  livenessProbe:
    enabled: true

  # democratic-csi node
  driver:
    enabled: true
    image: docker.io/democraticcsi/democratic-csi:v1.6.0
    # imagePullPolicy: Always
    logLevel: debug
    # set path to null if your OS has no localtime file
    # RancherOS, openshift, etc 
    localtimeHostPath: /etc/localtime
    lifecycle:
#      postStart:
#        exec:
#          command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
#      preStop:
#        exec:
#          command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]

    extraEnv: []
    extraVolumeMounts: []
#    - name: foo
#      mountPath: /foo
  
  # https://kubernetes-csi.github.io/docs/node-driver-registrar.html
  driverRegistrar:
    enabled: true
    image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
    logLevel: debug
    args:
    - --v=5
    - --csi-address=/csi-data/csi.sock
    - --kubelet-registration-path={{ .Values.node.kubeletHostPath }}/plugins/{{ .Values.csiDriver.name }}/csi.sock
    # if you do not want to completely override the defaults use this
    extraArgs: []

  extraVolumes: []
#  - name: foo
#    hostPath:
#      path: /dev
#      type: Directory

  nodeSelector: {}

  tolerations: []

  affinity: {}

# add note here about volume expansion requirements
storageClasses:
- name: freenas-nfs-csi
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: nfs

  mountOptions:
  - noatime
  - nfsvers=4

volumeSnapshotClasses: []
#- name:
#  annotations: {}
#  labels: {}
#  deletionPolicy: Delete | Retain
#  parameters:
#  secrets:
#    snapshotter-secret:

csiProxy:
  enabled: true
  image: docker.io/democraticcsi/csi-grpc-proxy:v0.3.0
