kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-sonarqube
  namespace: dev
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
