apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: git
  namespace: dev
  labels:
    app.kubernetes.io/instance: gitea
spec:
  dnsNames:
    - git.champiat.lan
  secretName: git-tls
  issuerRef:
    name: web-ca-issuer
    kind: ClusterIssuer